services:
  - type: worker
    name: telegram-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python verify.py
    plan: free
    envVars:
      - key: API_TOKEN
        sync: false
